upload:
  script:
    - echo "hello"

  after_script:
    - git config credential.helper 'store --file .my-credentials'
    - echo ".my-credentials" >> .gitignore
    - echo "https://$($github_token):x-oauth-basic@github.com`n"
    - git remote add origin https://github.com/npretto/gitlab_to_github.git
    - git push github --all
    - rm .my-credentials